### ISSUE TITLE
Type ID is neither a built-in type, nor refers to another model, custom type, or enum.

### ISSUE THREAD

**Issue by victordombrovskiy** [prisma/lift#212] opened 2019-11-13 04:24 UTC
Starting from v015 I face the following error:

```
"Type \"ID\" is neither a built-in type, nor refers to another model, custom type, or enum.",
```

due to the following in prisma file:

```
type ID = String @default(cuid()) @id @unique

model User {
  id                    ID
}
```

it was working up to v015. The issue is present in v015 and v016.

**Comment by pantharshit00** [comment] 2019-11-15 11:27
Hi,

Thanks for reporting this but this has been already reported once. So I am going to close this as a duplicate of https://github.com/prisma/prisma2/issues/896

**Closed by pantharshit00** 2019-11-15 11:27 UTC
Labels: process/candidate
