### ISSUE TITLE
Cannot Get Lift to work with PostgreSQL on Mac OS

### ISSUE THREAD

**Issue by dillonparfitt** [prisma/lift#113] opened 2019-08-29 10:25 UTC
I am attempting to get Lift to work on macOS X with PostgreSQL version 11.4.

When running:
```
export DEBUG="*"
prisma2 lift save
```

My schema.prisma file is: 

```
datasource db {
  provider = "postgresql"
  url      = env("POSTGRESQL_URL")
}

generator photonjs {
  provider = "photonjs"
}

model User {
  id        Int      @id
  createdAt DateTime @default(now())
  email     String   @unique
  name      String?
  role      Role     @default(USER)
  posts     Post[]
}

model Post {
  id         Int        @id
  createdAt  DateTime   @default(now())
  updatedAt  DateTime   @updatedAt
  author     User
  title      String
  published  Boolean    @default(false)
}

enum Role {
  USER
  ADMIN
}
```

I get the following output:

```
2019-08-29T09:56:23.879Z LiftEngine:rpc SENDING RPC CALL { id: 1,
  jsonrpc: '2.0',
  method: 'listMigrations',
  params:
   { projectInfo: '',
     sourceConfig:
      'datasource db {\n  provider = "postgresql"\n  url      = env("POSTGRESQL_URL")\n}\n\ngenerator photonjs {\n  provider = "photonjs"\n}\n\nmodel User {\n  id        Int      @id\n  createdAt DateTime @default(now())\n  email     String   @unique\n  name      String?\n  role      Role     @default(USER)\n  posts     Post[]\n}\n\nmodel Post {\n  id         Int        @id\n  createdAt  DateTime   @default(now())\n  updatedAt  DateTime   @updatedAt\n  author     User\n  title      String\n  published  Boolean    @default(false)\n}\n\nenum Role {\n  USER\n  ADMIN\n}' } }
2019-08-29T09:56:23.898Z LiftEngine:stderr thread 'main' panicked at 'Box<Any>', migration-engine/core/src/main.rs:55:23
2019-08-29T09:56:23.898Z LiftEngine:stderr stack backtrace:
2019-08-29T09:56:23.931Z LiftEngine:stderr    0: std::panicking::default_hook::{{closure}}
2019-08-29T09:56:23.932Z LiftEngine:stderr    1: std::panicking::default_hook
2019-08-29T09:56:23.932Z LiftEngine:stderr    2: std::panicking::rust_panic_with_hook
2019-08-29T09:56:23.932Z LiftEngine:stderr    3: std::panicking::begin_panic
2019-08-29T09:56:23.933Z LiftEngine:stderr    4: migration_engine::main
2019-08-29T09:56:23.933Z LiftEngine:stderr    5: std::rt::lang_start::{{closure}}
2019-08-29T09:56:23.933Z LiftEngine:stderr    6: std::panicking::try::do_call
2019-08-29T09:56:23.933Z LiftEngine:stderr    7: __rust_maybe_catch_panic
2019-08-29T09:56:23.933Z LiftEngine:stderr    8: std::rt::lang_start_internal
2019-08-29T09:56:23.933Z LiftEngine:stderr    9: main
Error: Error: Error in migration engine: thread 'main' panicked at 'Box<Any>', migration-engine/core/src/main.rs:55:23
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic
   4: migration_engine::main
   5: std::rt::lang_start::{{closure}}
   6: std::panicking::try::do_call
   7: __rust_maybe_catch_panic
   8: std::rt::lang_start_internal
   9: main
    at ChildProcess.child.on (/Users/dillonparfitt/.nvm/versions/node/v10.16.1/lib/node_modules/prisma2/build/index.js:114569:37)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

**Comment by pantharshit00** [comment] 2019-08-29 11:02
Duplicate of https://github.com/prisma/prisma2/issues/381

Make sure that environment variable is available.

**Closed by pantharshit00** 2019-08-29 11:02 UTC
