### ISSUE TITLE
prisma2 lift save hangs on first call

### ISSUE THREAD

**Issue by MichalLytek** [prisma/lift#221] opened 2019-11-27 12:55 UTC
```
datasource db {
  provider = "sqlite"
  url      = "file:../dev.db"
}
```
When I run `npx prisma2 lift save --name 'init'` on a new project, it asks to create a sqlite db file and then hangs in terminal exactly cutting some words:
```
You are trying to create a migration for Sqlite database d
```

I have to ctrl+c to kill the command and then on 2nd run it creates a migration properly.

As a sidenote it create a db file in the cwd, not in the proper path, so in git I have a good file and a one empty file.

**Comment by timsuchanek** [comment] 2019-11-27 12:58
Note, that this happens on a windows machine.

**Comment by pantharshit00** [comment] 2019-11-27 14:43
Hi,

Thanks for reporting this but this has been already reported once. So I am going to close this as a duplicate of https://github.com/prisma/lift/issues/219

**Closed by pantharshit00** 2019-11-27 14:43 UTC
Labels: bug/2-confirmed, kind/bug, process/candidate

**Comment by pantharshit00** [comment] 2019-11-27 14:44
@timsuchanek I was also able to reproduce the issue on Mac with the detailed info from the other ticket. It is related to relative paths.
