### ISSUE TITLE
prism2 lift doesn't account port of postgres database

### ISSUE THREAD

**Issue by kpilard** [prisma/lift#18] opened 2019-06-22 20:25 UTC
Hey

I try to connect my local postgres Database to lift. I think the lift commands ignore the configured port.

### Command finishes with default port
```
docker run --rm -d -e POSTGRES_PASSWORD="secret" -p 5432:5432
prisma2 lift save

datasource db {
  provider = "postgres"
  url      = "postgresql://postgres:secret@127.0.0.1:5432/postgres?schema=public"
}
```

### Command doen't finish with custom port 
```
docker run --rm -d -e POSTGRES_PASSWORD="secret" -p 5433:5432
prisma2 lift save

datasource db {
  provider = "postgres"
  url      = "postgresql://postgres:secret@127.0.0.1:5433/postgres?schema=public"
}
```

### Command finishes if db runs on default port but a custom port is configured 
```
docker run --rm -d -e POSTGRES_PASSWORD="secret" -p 5432:5432
prisma2 lift save

datasource db {
  provider = "postgres"
  url      = "postgresql://postgres:secret@127.0.0.1:5433/postgres?schema=public"
}
```

**Comment by matthewmueller** [comment] 2019-06-27 15:51
Hi @kpilard 

Are you seeing this issue? https://github.com/prisma/lift/issues/10

**Comment by kpilard** [comment] 2019-06-27 16:40
@matthewmueller Yes i'm seeing the issue. Was it hidden before?
Seems to be the same error
``````

**Comment by pantharshit00** [comment] 2019-06-27 17:27
Looks like a duplicate to me. @matthewmueller I think we can close this as a duplicate of #10

**Closed** 2019-07-04 13:44 UTC
Labels: bug/0-needs-info, kind/bug, team/engineering
