### ISSUE TITLE
Lift fails to locate existing database

### ISSUE THREAD

**Issue by artemzakharov** [prisma/lift#173] opened 2019-10-12 23:44 UTC
After updating to preview 14, I'm seeing the following issue when I attempt to run `prisma2 lift save`:

```
You are trying to create a migration for a PostgreSQL database foo-1.
A database with that name doesn't exist at XXX.XXX.XXX.XX:XXXX.
Do you want to create the database?
```
The database exists and no such error occurred prior to updating to preview 14.

**Comment by pantharshit00** [comment] 2019-10-14 17:38
Hi @artemzakharov 

Thanks for reporting this but this has already been reported here: https://github.com/prisma/prisma2/issues/694

Since that issue now has more context, I am going to close this issue as a duplicate of that issue.

**Closed by pantharshit00** 2019-10-14 17:38 UTC
