### ISSUE TITLE
Prisma2 fails if schema contains multiple rels between same types

### ISSUE THREAD

**Issue by victordombrovskiy** [prisma/lift#75] opened 2019-07-13 12:15 UTC
My schema has two rels between User and Event: 
- userIsCreatorOfEvent
- userIsOrganiserOfEvent

To disambiguate this I use  @relation attribute. But it doesn't work:
```
model User {
  id                    String      @default(cuid()) @id @unique
  name                  String
  createdEvents         Event[]     @relation(name: "userIsCreatorOfEvent")
  organisedEvents       Event[]     @relation(name: "userIsOrganiserOfEvent")
}

model Event {
  id                    String      @default(cuid()) @id @unique
  name                  String
  creator               User        @relation(name: "userIsCreatorOfEvent")
  organiser             User        @relation(name: "userIsOrganiserOfEvent")
}
```

It throws the following error:

```
Error: process exited with a non-zero code: 101
thread 'main' panicked at 'Did not find a relation for those for model Event and field organiser', src/libcore/option.rs:1034:5
```

**Comment by mavilein** [comment] 2019-08-02 15:50
I can't reproduce this anymore. This was probably fixed by improvements i made in the parser recently.

**Closed by mavilein** 2019-08-02 15:50 UTC
Labels: bug/2-confirmed, kind/bug
