### ISSUE TITLE
`prisma2 lift up` runs into "Error in lift engine for rpc calculateDatabaseSteps"

### ISSUE THREAD

**Issue by nickreynke** [prisma/lift#88] opened 2019-08-02 05:26 UTC
Steps to reproduce (hopefully):

* Start the development mode `prisma2 dev`
* Modify the `schema.prisma` file. (For me it was adding the `Post` model and a relationship between `User` and `Post`; [following the Tutorial](https://github.com/prisma/prisma2/blob/master/docs/tutorial.md#84-terminate-development-mode-and-migrate-with-lift))
* Exit the development mode by hitting <kbd>CTRL</kbd>+<kbd>C</kbd> twice.
* Run `prisma2 lift save --name 'add-post'` to create new migration files.
* Run `prisma2 lift up` which throws the error mentioned below.

> May be a duplicate of the other `lift up` errors. Not sure.

Running with Prisma version: **2.0.0-preview-3.2**

# Failed calculateDatabaseSteps at 2019-08-01T15:57:05.193Z
## RPC Input One Line
```json
{"id":1,"jsonrpc":"2.0","method":"calculateDatabaseSteps","params":{"projectInfo":"","assumeToBeApplied":[{"stepType":"CreateModel","name":"User","embedded":false},{"stepType":"CreateField","model":"User","name":"id","type":{"Base":"String"},"arity":"required","isUnique":false,"id":{"strategy":"Auto","sequence":null},"default":{"Expression":["cuid","String",[]]}},{"stepType":"CreateField","model":"User","name":"name","type":{"Base":"String"},"arity":"optional","isUnique":false},{"stepType":"CreateField","model":"User","name":"email","type":{"Base":"String"},"arity":"required","isUnique":true}],"stepsToApply":[{"stepType":"CreateField","model":"User","name":"posts","type":{"Relation":{"to":"Post","to_fields":[],"name":"PostToUser","on_delete":"None"}},"arity":"list","isUnique":false},{"stepType":"CreateField","model":"Post","name":"author","type":{"Relation":{"to":"User","to_fields":["id"],"name":"PostToUser","on_delete":"None"}},"arity":"optional","isUnique":false}],"sourceConfig":"datasource db {\n  provider = \"postgresql\"\n  url      = env(\"POSTGRES_URL\")\n}\n\ngenerator photonjs {\n  provider = \"photonjs\"\n}\n\nmodel User {\n  id    String  @id @default(cuid())\n  name  String?\n  email String  @unique\n  posts Post[]\n}\n\nmodel Post {\n  id        String  @id @default(cuid())\n  title     String\n  published Boolean @default(false)\n  author    User?\n}"}}
```

## RPC Input Readable
```json
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "calculateDatabaseSteps",
  "params": {
    "projectInfo": "",
    "assumeToBeApplied": [
      {
        "stepType": "CreateModel",
        "name": "User",
        "embedded": false
      },
      {
        "stepType": "CreateField",
        "model": "User",
        "name": "id",
        "type": {
          "Base": "String"
        },
        "arity": "required",
        "isUnique": false,
        "id": {
          "strategy": "Auto",
          "sequence": null
        },
        "default": {
          "Expression": [
            "cuid",
            "String",
            []
          ]
        }
      },
      {
        "stepType": "CreateField",
        "model": "User",
        "name": "name",
        "type": {
          "Base": "String"
        },
        "arity": "optional",
        "isUnique": false
      },
      {
        "stepType": "CreateField",
        "model": "User",
        "name": "email",
        "type": {
          "Base": "String"
        },
        "arity": "required",
        "isUnique": true
      }
    ],
    "stepsToApply": [
      {
        "stepType": "CreateField",
        "model": "User",
        "name": "posts",
        "type": {
          "Relation": {
            "to": "Post",
            "to_fields": [],
            "name": "PostToUser",
            "on_delete": "None"
          }
        },
        "arity": "list",
        "isUnique": false
      },
      {
        "stepType": "CreateField",
        "model": "Post",
        "name": "author",
        "type": {
          "Relation": {
            "to": "User",
            "to_fields": [
              "id"
            ],
            "name": "PostToUser",
            "on_delete": "None"
          }
        },
        "arity": "optional",
        "isUnique": false
      }
    ],
    "sourceConfig": "datasource db {\n  provider = \"postgresql\"\n  url      = env(\"POSTGRES_URL\")\n}\n\ngenerator photonjs {\n  provider = \"photonjs\"\n}\n\nmodel User {\n  id    String  @id @default(cuid())\n  name  String?\n  email String  @unique\n  posts Post[]\n}\n\nmodel Post {\n  id        String  @id @default(cuid())\n  title     String\n  published Boolean @default(false)\n  author    User?\n}"
  }
}
```

## RPC Response
```
null
```

## Stack Trace
```bash
[migration-engine/connectors/sql-migration-connector/src/lib.rs:391] format!("CREATE SCHEMA IF NOT EXISTS \"{}\";" , & self . schema_name) = "CREATE SCHEMA IF NOT EXISTS \"public\";"
[migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:39] m.make_from(barrel_variant) = "CREATE TABLE \"public\".\"_Migration\" (\"revision\" SERIAL PRIMARY KEY NOT NULL, \"name\" TEXT NOT NULL, \"datamodel\" TEXT NOT NULL, \"status\" TEXT NOT NULL, \"applied\" INTEGER NOT NULL, \"rolled_back\" INTEGER NOT NULL, \"datamodel_steps\" TEXT NOT NULL, \"database_migration\" TEXT NOT NULL, \"errors\" TEXT NOT NULL, \"started_at\" timestamp(3) NOT NULL, \"finished_at\" timestamp(3));"
thread 'main' panicked at 'The model Post does not exist in this Datamodel. It is not possible to create a field in it.', src/libcore/option.rs:1034:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::option::expect_failed
   9: <migration_core::migration::datamodel_calculator::DataModelCalculatorImpl as migration_core::migration::datamodel_calculator::DataModelCalculator>::infer
  10: <migration_core::commands::calculate_database_steps::CalculateDatabaseStepsCommand as migration_core::commands::command::MigrationCommand>::execute
  11: <F as jsonrpc_core::calls::RpcMethodSimple>::call
  12: <F as jsonrpc_core::calls::RpcMethod<T>>::call
  13: <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll
  14: <futures::future::then::Then<A,B,F> as futures::future::Future>::poll
  15: <futures::future::map::Map<A,F> as futures::future::Future>::poll
  16: <futures::future::either::Either<A,B> as futures::future::Future>::poll
  17: futures::task_impl::std::set
  18: std::thread::local::LocalKey<T>::with
  19: futures::future::Future::wait
  20: jsonrpc_core::io::IoHandler<M>::handle_request_sync
  21: migration_core::rpc_api::RpcApi::handle
  22: migration_engine::main
  23: std::rt::lang_start::{{closure}}
  24: std::panicking::try::do_call
  25: __rust_maybe_catch_panic
  26: std::rt::lang_start_internal
  27: main

```

**Comment by nickreynke** [comment] 2019-08-02 19:21
After completely re-setting up my Postgres, removing the migration within the migrations directory (and from within the `lift.lock` file) and then running `prisma2 lift save --name 'add-post'` and then `prisma2 lift up` it worked.

```
Database Changes:

Migration                Database actions           Status

20190801153006-init      1 CreateTable statements.  Done 🚀
20190802211859-add-post  1 CreateTable statements.  Done 🚀

You can get the detailed db changes with prisma2 lift up --verbose
Or read about them in the ./migrations/MIGRATION_ID/README.md

🚀  Done with 2 migrations in 759ms.
```

**Comment by ManAnRuck** [comment] 2019-08-04 18:35
`rm -rf node_modules`
`yarn install`

this was my solution with an sqlite database

**Comment by divyenduz** [comment] 2019-08-05 13:34
With exactly these steps

* Start the development mode `prisma2 dev`
* Modify the `schema.prisma` file. (For me it was adding the `Post` model and a relationship between `User` and `Post`; [following the Tutorial](https://github.com/prisma/prisma2/blob/master/docs/tutorial.md#84-terminate-development-mode-and-migrate-with-lift))
* Exit the development mode by hitting <kbd>CTRL</kbd>+<kbd>C</kbd> twice.
* Run `prisma2 lift save --name 'add-post'` to create new migration files.
* Run `prisma2 lift up` which throws the error mentioned below.

I was unable to reproduce this. Did models other that the post connection exist then in the DB already? That is what I tried. 

However, trying a `prisma2 dev` without anything in the DB yielded the following error for me

```
Error: Error: Error in lift engine for rpc inferMigrationSteps:
  thread 'main' panicked at 'The field posts on model User already exists in this Datamodel. It is not possible to create it once more.', migration-engine/core/src/migration/datamodel_calculator.rs:143:9
```

Which is similar but not the same, so not marking this as a repro yet. We need to spend more time on this.

**Comment by pantharshit00** [comment] 2019-08-05 20:06
I can reproduce this and I think this is a duplicate of https://github.com/prisma/prisma2/issues/37

That issue was lacking a concrete reproduction but I guess we got a reproduction now. So I think what is happening here is lift is unable to determine the state of the migration whether they are applied or not and trying to apply the whole set even though they are in the database. I think lift flow and dev flow are not behaving separately here and it is the same issue.

@divyenduz should we close this issue as a duplicate?

**Comment by divyenduz** [comment] 2019-08-06 08:17
@pantharshit00 if you strongly believe that this is a duplicate, please feel free to close it and post the reproduction on the open issue.

**Comment by janpio** [comment] 2019-09-02 14:31
@pantharshit00 Now both this issue and https://github.com/prisma/prisma2/issues/37 are `0-needs-info` and are still open. Please consolidate and/or retest this to make sure there is actually one actionable issue. Thanks.

**Comment by pantharshit00** [comment] 2019-09-03 12:27
I no longer can reproduce these issues, closing!

**Closed by pantharshit00** 2019-09-03 12:27 UTC
Labels: bug/0-needs-info, kind/bug
