### ISSUE TITLE
Lift save/up hangs at creating SQLite db

### ISSUE THREAD

**Issue by marcjulian** [prisma/lift#219] opened 2019-11-24 12:53 UTC
The command `prisma2 lift save` and `prisma2 lift up` hangs at `Creating database ....`.

![Screenshot 2019-11-24 at 13 47 29](https://user-images.githubusercontent.com/8985933/69494933-7e613c00-0ec1-11ea-907f-9b339d5b6487.png)

This behavior exists in the following versions I tested:
prisma2@2.0.0-preview016.2, binary version: b72fd0a786adc77ba6c61d0a9637ff0371e433b0
prisma2@2.0.0-alpha.351, binary version: b8d90fea39d266b128b4d748db5aca8505bb1026

It still works with the version prisma2@2.0.0-preview016, binary version: 377e2db71bae5da19d0090558c8819ff57dfdfc6

**Env**
Mac 10.14.6

**Comment by pantharshit00** [comment] 2019-11-25 16:47
I am unable to reproduce this. Can you please share your datamodel with us?

**Comment by marcjulian** [comment] 2019-11-25 20:00
Of course, it appears in this project https://github.com/fivethree-team/nestjs-prisma-starter/tree/prisma2

```
datasource db {
  provider = "sqlite"
  url      = "file:../db/dev.db"
}

generator photon {
  provider = "photonjs"
}

model User {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  email     String   @unique
  password  String
  firstname String?
  lastname  String?
  posts     Post[]
  role      Role
}

model Post {
  id        String   @default(cuid()) @id @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  published Boolean
  title     String
  content   String?
  author    User?
}

enum Role {
  ADMIN
  USER
}
```

**Comment by pantharshit00** [comment] 2019-11-26 17:45
I can confirm this bug.

I think it is related to https://github.com/prisma/prisma2/issues/936#issuecomment-558578657 so for the time being don't use a relative path.

**Comment by marcjulian** [comment] 2019-11-26 19:29
Thanks for looking into the issue

**Comment by timsuchanek** [comment] 2019-12-13 14:55
Thanks a lot for reporting 🙏
This issue is fixed in the latest alpha version of `prisma2`.
You can try it out with `npm i -g prisma2@alpha`.

In case it’s not fixed for you - please let us know and we’ll reopen this issue!

**Comment by marcjulian** [comment] 2019-12-13 15:26
I tested it with prisma2 version  2.0.0-alpha.453 and hangs at creating the db at path `file:../db/dev.db`

**Comment by pantharshit00** [comment] 2019-12-19 15:56
I can confirm this is still an issue.
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/22195362/71187835-de22eb00-22a5-11ea-9344-d22ccfafa7d1.png">


(Note: only happens now when folder db doesn't exists)

**Comment by timsuchanek** [comment] 2020-01-14 10:55
This is a problem in the create database RPC of the migration engine.

**Closed** 2020-01-15 12:36 UTC
Labels: bug/2-confirmed, kind/bug

**Comment by tomhoule** [comment] 2020-01-15 12:37
This is fixed by https://github.com/prisma/prisma-engine/pull/379 - it should be in the next alpha release :)
